config/routes.rb
Rails.application.routes.draw do
  get 'orders/index'
  get 'current_user/index'
  # devise_for :users, path: '', path_names: {
  #   sign_in: 'login',
  #   sign_out: 'logout',
  #   registration: 'signup'
  # },
  #  controllers: {
  #   sessions: 'users/sessions',
  #   registrations: 'users/registrations'
  # }
  # devise_for :users, controllers: {
  #    sessions: 'users/sessions',
  #   registrations: 'users/registration'
  # }
  # scope :api, defaults: { format: :json } do
  #   scope :v1 do
  #     devise_for :users
  #   end
  # end
  namespace :api do
    namespace :v1 do
      devise_for :users, controllers: {
        sessions: 'api/v1/users/sessions',
        registrations: 'api/v1/users/registrations'
      }, path: '',path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      registration: 'signup'
    }
    end
  end
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get 'current_user/index'

  default_url_options :host => "localhost:3000"
  namespace :api do
    namespace :v1 do
     
      # get 'products/index'
      # get 'products/create'
      
       resources :products, only: [:index, :show]
       # only: [:show, :create, :index]
       # get 'products/show'
       get 'carts/index'
       get 'carts/show'
       # get 'carts/create'
       # get 'carts/address', to: 'carts#address'

      resources :carts do 
        post "address_create", on: :collection
      end

      namespace :admin do
        resources :products, only: [:create, :update, :destroy]
      end

      get '/order_items/:product_id/add_to_cart', to: 'order_items#add_to_cart', as: :add_to_cart
      delete '/order_items/:id', to: 'order_items#destroy', as: :remove_order_item


    end
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'home/index'
  get 'home/users'
  get 'home/about'
  # resources :users;
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "home#index"
  # resources :order_items do
  #   member do
  #     post 'add_to_cart' 
  #   end
  # end
  
  get '/products', to: 'home#index'
  #get '/search', to: 'home#search'

  get '/order_items/:product_id/add_to_cart', to: 'order_items#add_to_cart', as: :add_to_cart
  delete '/order_items/:id', to: 'order_items#destroy', as: :remove_order_item

  
  #resources :carts
  #get "/carts" , to: "carts#show"
  resources :carts, only: :index
  get '/cart', to: 'carts#cart', as: :cart
  get '/carts/address', to: 'carts#address'
  post 'carts/address_create', to: 'carts#address_create'
  delete 'carts/address_destroy', to: 'carts#remove_address'
  put '/assign_address', to: 'carts#assign_address'
  get '/carts/payment', to: 'carts#payment'
  post 'carts/payment_success', to: 'carts#payment_success'
  get '/carts/complete', to: 'carts#complete'


  delete 'api/v1/carts/remove_address/:id', to: 'api/v1/carts#remove_address'
end

app/controllers/api/v1/carts_controller.rb
class Api::V1::CartsController < Api::V1::ApiApplicationController

  def index
    orders = Order.all
    render json: orders, status:200
  end
  

  def show
  end

  def address
    add_address = Address.new
    render json: add_address, status:200
  end

  def address_create
    @address = current_user.addresses.new(address_params)
    if @address.save
       return render json: @address ,status: :ok
    else
      return render json: @address.errors, status: :unprocessable_entity
    end
  end

  def remove_address
    @address = Address.find(params[:id])
    if @address.destroy
      render json: {message: 'address deleted successfully' }
    end
  end

  def create
  end

  private
  def address_params
    params.permit(:full_name, :phone_number, :pin_code, :district, :state, :city, :house_no, :colony_name)
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	
  before_action :find_order
  before_action :find_all_address, only: [:address, :address_create]

  def cart
  	
	end

	def index
		respond_to do |format|
			format.html{
				orders = Order.all
			}

			format.json{
				render json: Order.all
			}
		end
	end

	def address
    @new_address = Address.new
	end


	def address_create
		@address = current_user.addresses.new(address_params)
    if @address.save
			redirect_to carts_address_path
		else
			render :address, status: :unprocessable_entity
		end
	end

	def remove_address
    @address = Address.find(params[:address_id])
    if @address.destroy
      redirect_to carts_address_path, notice: "address removed"
    end
  end

  def assign_address
    @order.update(assign_address_params)
    redirect_to  carts_payment_path
  end


	def payment
		razorpay_payment = RazorpayPayment.new
		razorpay_order = razorpay_payment.create_razorpay_order(@order.total.to_i*100)
		if razorpay_order.id
			@order.update(razorpay_order_id: razorpay_order.id)
		end
	end

	def payment_success
		razorpay_payment = RazorpayPayment.new
		response = razorpay_payment.verify_payment_status(params[:razorpay_order_id], params[:razorpay_payment_id], params[:razorpay_signature])
		if response
			@order.update(status: :complete)
			OrderMailer.order_completed(current_user).deliver_now
			phone = @order.address.phone_number.to_s
			code = "+91"
			phone_code = code + phone
			t= TwilioSms.new(phone_code,"hii")
			t.send_message
			redirect_to carts_complete_path
		end
	end

	def complete

	end

	def destroy
	end

	

	
	private
	def address_params
		params.require(:address).permit(:full_name, :phone_number, :pin_code, :district, :state, :city, :house_no, :colony_name)
	end

  def assign_address_params
    params.require(:order).permit(:address_id)
  end

  def find_order
    @order = current_user.orders.where.not(status: 'complete').first
  end

  def find_all_address
    @addresses = current_user.addresses
  end
end

app/helpers/api/v1/carts_helper.rb
module Api::V1::CartsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/address.html.erb
<style>
	.abc{
		display: flex;
		justify-content: space-between;
		max-width: 1200px;
		margin: 0 auto;
	}

</style>


<div class="abc">
<div class="split left">
	<div class="centered">

		<h1>previous address  </h1> 
    
  		<div>
      <%= form_with model: @order, url: assign_address_path, method: 'put', local: true do |form| %>   
  			<% @addresses.each do |address| %>  
        <div class="container border">
          <%= form.radio_button :address_id, address.id %>
            <%= address.full_name %> ,
            <%= address.phone_number %> ,
            pi_code: <%= address.pin_code %> ,
            <%= address.district %> ,
            <%= address.state %> ,
            <%= address.city %> ,
            <%= address.house_no %> ,
            <%= address.colony_name %> 
            <%= link_to 'delete', carts_address_destroy_path(address_id: address.id), method: :delete %>
            <!-- data: { "turbo-method": :delete } -->
          <br/><br/><br/>
        </div>
        <% end %>
        <%= form.submit 'Next' %>
      <% end %>
  		</div>
    
		

	</div>
</div>



<div class="split right">
  <div class="centered">
  <%= form_with model: @new_address, url: carts_address_create_path, local: true do |form| %>
	 <h2>New Address</h2>
	<div>
		<%= form.label :full_name %><br>
		<%= form.text_field :full_name %>
	</div>

	<div>
		<%= form.label :phone_number %><br>
		<%= form.text_field :phone_number %>
	</div>

	<div>
		<%= form.label :pin_code %><br>
		<%= form.text_field :pin_code %>
	</div>


	<div>
		<%= form.label :district %><br>
		<%= form.text_field :district %>
	</div>

	
	<div>
		<%= form.label :state %><br>
		<%= form.text_field :state %>
	</div>

	<div>
		<%= form.label :city %><br>
		<%= form.text_field :city %>
	</div>

	<div>
		<%= form.label :house_no %><br>
		<%= form.text_field :house_no %>
	</div>

	<div>
		<%= form.label :colony_name %><br>
		<%= form.text_field :colony_name %>
	</div>
	
	<div>
		<%= form.submit %>
	</div>
  <% end %>

  </div>
</div>
</div>
	

app/views/carts/cart.html.erb
<% if @order.present? %>
	<table class="table">
  <thead>
    <tr>
      <th scope="col">Product</th>
      <th scope="col">Quantity</th>
      <th scope="col">Price</th>      
      <th scope="col">Action</th>
    </tr>
  </thead>
  <% @order.order_items.each do |order_item| %>
  <tbody>
    <tr>
      <th scope="row"><%= order_item.product.name %></th>
      <td><%= order_item.quantity %></td>
      <td><%= order_item.price %></td>
      
      
      <td>
        <%#= link_to 'Remove item', remove_order_item_path(order_item), method: :delete, data: { confirm: "Are you sure?" } %>
        <%= link_to 'Remove item', remove_order_item_path(order_item), data: { method: :delete } %>
      </td>
    </tr>
    <% end %>  
      <th scope="row"></th>
      <th scope="row"></th>
      <td colspan="2">Total price: <%= @order.total %></td>
    </tr>
  </tbody>
</table>

	<% else %>

		<div>
			<h1>There is no any item selected </h1>
		</div>
	<% end %>


<br>

<%= link_to "Next", carts_address_path %>



	

app/views/carts/complete.html.erb
<h1>completed</h1>
<h3 style = "color:green;">Ordered successfully</h3>

app/views/carts/index.html.erb
<h3 style = "color:green;">Ordered successfully</h3>
<h5>Order Summary</h5>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Product</th>
      <th scope="col">Quantity</th>
      <th scope="col">Price</th>      
    </tr>
  </thead>
  <% @order.order_items.each do |order_item| %>
  <tbody>
    <tr>
      <th scope="row"><%= order_item.product.name %></th>
      <td><%= order_item.quantity %></td>
      <td><%= order_item.price %></td>
      
    </tr>
    <% end %>  
      <th scope="row"></th>
      <th scope="row"></th>
      <td colspan="2">Total price: <%= @order.total %></td>
    </tr>
  </tbody>
</table>


<div>
    <%= form_tag(carts_payment_success_path, method: :post, id: "complete-form") do |form| %>
        <%= hidden_field_tag 'razorpay_payment_id', '' %>
        <%= hidden_field_tag 'razorpay_signature', ''%>
        <%= hidden_field_tag 'razorpay_order_id', '' %>
    <% end %>
</div>



<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script>
var options = {
    "key": "rzp_test_ZrT7bSS6LMCvO2",
    "amount": "<%= @order.total.to_i*100 %>", 
    "currency": "INR",
    "order_id": "<%= @order.razorpay_order_id %>", 
    "handler": function (response){
        // $.ajax('/carts/payment_success',
        //     type: 'POST',
        //     data: { 
        //     "razorpay_order_id": response.razorpay_order_id,
        //     "razorpay_payment_id": response.razorpay_payment_id,
        //     "razorpay_signature": ""
        //      });


        
        $("#razorpay_payment_id").val(response.razorpay_payment_id)
        $("#razorpay_order_id").val(response.razorpay_order_id)
        $("#razorpay_signature").val(response.razorpay_signature)
        $("#complete-form").submit();
    },
    "prefill": {
        
        "email": "<%= current_user.email %>",
        
    },
    "notes": {
        "address": "Razorpay Corporate Office"
    },
    "theme": {
        "color": "#3399cc"
    }
};
var rzp1 = new Razorpay(options);
rzp1.on('payment.failed', function (response){
        alert(response.error.code);
        alert(response.error.description);
        alert(response.error.source);
        alert(response.error.step);
        alert(response.error.reason);
        alert(response.error.metadata.order_id);
        alert(response.error.metadata.payment_id);
});
document.getElementById('rzp-button1').onclick = function(e){
    rzp1.open();
    e.preventDefault();
}
</script>

app/views/carts/payment.html.erb
<h1>Order Summary</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Product</th>
      <th scope="col">Quantity</th>
      <th scope="col">Price</th>      
    </tr>
  </thead>
  <% @order.order_items.each do |order_item| %>
  <tbody>
    <tr>
      <th scope="row"><%= order_item.product.name %></th>
      <td><%= order_item.quantity %></td>
      <td><%= order_item.price %></td>
      
    </tr>
    <% end %>  
      <th scope="row"></th>
      <th scope="row"></th>
      <td colspan="2">Total price: <%= @order.total %></td>
    </tr>
  </tbody>
</table>


<div>
    <%= form_tag(carts_payment_success_path, method: :post, id: "complete-form") do |form| %>
        <%= hidden_field_tag 'razorpay_payment_id', '' %>
        <%= hidden_field_tag 'razorpay_signature', ''%>
        <%= hidden_field_tag 'razorpay_order_id', '' %>
    <% end %>
</div>


<button id="rzp-button1">Pay Now</button>
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script>
var options = {
    "key": "rzp_test_jgok7moG1vXEGD",
    "amount": "<%= @order.total.to_i*100 %>", 
    "currency": "INR",
    "order_id": "<%= @order.razorpay_order_id %>", 
    "handler": function (response){
        // $.ajax('/carts/payment_success',
        //     type: 'POST',
        //     data: { 
        //     "razorpay_order_id": response.razorpay_order_id,
        //     "razorpay_payment_id": response.razorpay_payment_id,
        //     "razorpay_signature": ""
        //      });


        
        $("#razorpay_payment_id").val(response.razorpay_payment_id)
        $("#razorpay_order_id").val(response.razorpay_order_id)
        $("#razorpay_signature").val(response.razorpay_signature)
        $("#complete-form").submit();
    },
    "prefill": {
        
        "email": "<%= current_user.email %>",
        
    },
    "notes": {
        "address": "Razorpay Corporate Office"
    },
    "theme": {
        "color": "#3399cc"
    }
};
var rzp1 = new Razorpay(options);
rzp1.on('payment.failed', function (response){
        alert(response.error.code);
        alert(response.error.description);
        alert(response.error.source);
        alert(response.error.step);
        alert(response.error.reason);
        alert(response.error.metadata.order_id);
        alert(response.error.metadata.payment_id);
});
document.getElementById('rzp-button1').onclick = function(e){
    rzp1.open();
    e.preventDefault();
}
</script>


<%#= link_to "Next", carts_complete_path %>